### ISSUE TITLE
Isn't music too loud?

### ISSUE THREAD

**Issue by DCNick3** [caguiclajmg/platelet-clicker#3]
Well, the music SHOULD be background, but this one is at the same level as sound effects. Isn't it wrong?

**Comment by caguiclajmg** [comment]
It probably is, setting `snd_music`'s volume to 75% or something should be fine. Related: #4

**Comment by caguiclajmg** [comment]
Fixed by https://github.com/caguiclajmg/platelet-clicker/commit/f741b036c7a2163294f07277124295382936251c. Closing.
